version: "3.1"
services:
  web:
    build:
      context: ./client
      dockerfile: next.Dockerfile
    container_name: web
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./client:/next
      - /next/node_modules
      - /next/.next

  mongo:
    build:
      context: ./db
      dockerfile: db.Dockerfile
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME:${MONGO_ROOT_USER}
      - MONGO_INITDB_ROOT_PASSWORD:${MONGO_ROOT_PASSWORD}
    volumes:
      - db-data:/data/db

  mongo-express:
    image: mongo-express
    depends_on:
      - mongo
    restart: unless-stopped
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME:${MONGOEXPRESS_LOGIN}
      - ME_CONFIG_MONGODB_ADMINPASSWORD:${MONGOEXPRESS_PASSWORD}
      - ME_CONFIG_MONGODB_URL':mongodb://${MONGOEXPRESS_LOGIN}:{MONGOEXPRESS_PASSWORD}@mongo:27017/

volumes:
  db-data:
