version: "3.1"
services:
  # web:

  # backend:
  #   image: server
  #   restart: always
  #   ports:
  #     - 8008:8080

  mongo:
    build: ./db
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME:${MONGO_ROOT_USER}
      - MONGO_INITDB_ROOT_PASSWORD:${MONGO_ROOT_PASSWORD}
    volumes:
      - db-data:/data/db

  mongo-express:
    image: mongo-express
    depends_on:
      - mongo
    restart: unless-stopped
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME:${MONGOEXPRESS_LOGIN}
      - ME_CONFIG_MONGODB_ADMINPASSWORD:${MONGOEXPRESS_PASSWORD}
      - ME_CONFIG_MONGODB_URL':mongodb://${MONGOEXPRESS_LOGIN}:{MONGOEXPRESS_PASSWORD}@mongo:27017/

volumes:
  db-data:
